### ISSUE TITLE
Rultor script for pom.xml version

### ISSUE THREAD

**Issue by amihaiemil** [aliceice/paper#24]
Since you're using Rultor to release on Maven Central, you could as well have a script to update the version of the project in pom.xml or other links. [Here's](https://github.com/decorators-squad/camel/blob/master/rrv.sh) how I do it.

**Comment by aliceice** [comment]
Hi @amihaiemil,
Rultor updates the version in the pom.xml in the tag right?

I think that suffices for now.
But thanks for the hint!

**Comment by amihaiemil** [comment]
@aliceice rultor just releases the version (tag) that you give it, it does not update the pom.xml out of the box :)

**Comment by aliceice** [comment]
@amihaiemil As far as I can see it does: https://github.com/aliceice/paper/blob/1.1/pom.xml#L9

**Comment by amihaiemil** [comment]
Hmm, I didn't know it changes the version with the given tag. But I see it does it only for the released jar. It doesn't do it for the development repo, so thechnicaly you don't know what is the current version. From rultor's point of view the development version is always 0.0.1-SNAPSHOT, or whatever maven sets as default :D

**Comment by aliceice** [comment]
Have a look at https://github.com/aliceice/paper/blob/master/.rultor.yml#L25
This line changes the version and I think the development version does not really matter as it's development :)
